site_name: Fiori Tracker Business
nav:
    - Catalog Import: ci/SPS02/main.md
    - Apps Import: ai/FPS01/main.md
    - Mappings Import: mi/FPS01/main.md
    - Fiori Apps' Usage Report: fa.md
    - Installation: inst.md
    - Bugs or ideas: bugs-ideas.md
theme: 
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
plugins:
  - macros
  - search
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
extra:
  prod:
    ci:
      R2020FPS01:
        descr: 'Lets you import your catalogs from your system into the FT catalogs list'
        rel: 'FPS01'
        compatibleCoreLink: 'https://help.fioritracker.org/V2020/core/SPS02/main/'
        compatibleAsisMainLink: 'https://help.fioritracker.org/V2020/asis/FPS01/main/'
        compatibleAsisCenRel: 'FPS01'
        compatibleAsisCenLink: 'https://help.fioritracker.org/V2020/asis/FPS01/inst-cen/'
        compatibleAsisManRel: 'FPS01'
        compatibleAsisManLink: 'https://help.fioritracker.org/V2020/asis/FPS01/inst-man/'
      R2020SPS02:
        name: 'Catalog Import'
        descr: 'Lets you import your catalogs from your system into the FT catalogs list'
        rel: 'SPS02'
        compatibleCoreLink: 'https://help.fioritracker.org/V2020/core/SPS03/main/'
        compatibleAsisMainLink: 'https://help.fioritracker.org/V2020/asis/SPS02/main/'
        compatibleAsisCenRel: 'SPS02'
        compatibleAsisCenLink: 'https://help.fioritracker.org/V2020/asis/SPS02/inst-cen/'
        compatibleAsisManRel: 'SPS02'
        compatibleAsisManLink: 'https://help.fioritracker.org/V2020/asis/SPS02/inst-man/'
        rep: 'ci'
    ai:
      R2020FPS01:
        name: 'Apps Import'
        descr: 'Lets you import your apps from your system into the FT apps list'
        rel: 'FPS01'
        compatibleCoreLink: 'https://help.fioritracker.org/V2020/core/SPS03/main/'
        compatibleAsisMainLink: 'https://help.fioritracker.org/V2020/asis/SPS02/main/'
        compatibleAsisCenRel: 'SPS02'
        compatibleAsisCenLink: 'https://help.fioritracker.org/V2020/asis/SPS02/inst-cen/'
        compatibleAsisManRel: 'SPS02'
        compatibleAsisManLink: 'https://help.fioritracker.org/V2020/asis/SPS02/inst-man/'
        rep: 'ai'
    mi:
      R2020FPS01:
        name: 'Mappings Import'
        descr: 'Lets you import your apps to catalogs mappings from your system into the FT catalog apps relations'
        rel: 'FPS01'
        compatibleCoreLink: 'https://help.fioritracker.org/V2020/core/SPS03/main/'
        compatibleAsisMainLink: 'https://help.fioritracker.org/V2020/asis/SPS02/main/'
        compatibleAsisCenRel: 'SPS02'
        compatibleAsisCenLink: 'https://help.fioritracker.org/V2020/asis/SPS02/inst-cen/'
        compatibleAsisManRel: 'SPS02'
        compatibleAsisManLink: 'https://help.fioritracker.org/V2020/asis/SPS02/inst-man/'
        rep: 'mi'
    fa:
      R2020FPS01:
        name: 'Fiori Apps Usage Report'
        descr: 'Lets you import your apps to catalogs mappings from your system into the FT catalog apps relations'
        rel: 'FPS01'
        compatibleCoreLink: 'https://help.fioritracker.org/V2020/core/SPS03/main/'
        compatibleAsisMainLink: 'https://help.fioritracker.org/V2020/asis/SPS02/main/'
        compatibleAsisCenRel: 'SPS02'
        compatibleAsisCenLink: 'https://help.fioritracker.org/V2020/asis/SPS02/inst-cen/'
        compatibleAsisManRel: 'SPS02'
        compatibleAsisManLink: 'https://help.fioritracker.org/V2020/asis/SPS02/inst-man/'        
        rep: 'fa'
    fap:
      R2020FPS01:
        name: 'Fiori Apps Usage Plugin'
        descr: 'Lets you import your apps to catalogs mappings from your system into the FT catalog apps relations'
        rel: 'FPS01'
        compatibleCoreLink: 'https://help.fioritracker.org/V2020/core/SPS03/main/'
        compatibleAsisMainLink: 'https://help.fioritracker.org/V2020/asis/SPS02/main/'
        compatibleAsisCenRel: 'SPS02'
        compatibleAsisCenLink: 'https://help.fioritracker.org/V2020/asis/SPS02/inst-cen/'
        compatibleAsisManRel: 'SPS02'
        compatibleAsisManLink: 'https://help.fioritracker.org/V2020/asis/SPS02/inst-man/'
        rep: 'fap'
