site_name: Fiori Tracker Business
nav:
    - Catalog Import: ci/SPS02/main.md
    - Fiori Apps' Usage Report: fa.md
    - Installation: inst.md
theme: 
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
plugins:
  - macros
  - search
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
extra:
  prod:
    ci:
      R2020FPS01:
        rel: 'FPS01'
        compatibleCoreLink: 'https://help.fioritracker.org/V2020/core/SPS02/main/'
        compatibleAsisMainLink: 'https://help.fioritracker.org/V2020/asis/FPS01/main/'
        compatibleAsisCenRel: 'FPS01'
        compatibleAsisCenLink: 'https://help.fioritracker.org/V2020/asis/FPS01/inst-cen/'
        compatibleAsisManRel: 'FPS01'
        compatibleAsisManLink: 'https://help.fioritracker.org/V2020/asis/FPS01/inst-man/'
      R2020SPS02:
        rel: 'SPS02'
        compatibleCoreLink: 'https://help.fioritracker.org/V2020/core/SPS03/main/'
        compatibleAsisMainLink: 'https://help.fioritracker.org/V2020/asis/SPS02/main/'
        compatibleAsisCenRel: 'SPS02'
        compatibleAsisCenLink: 'https://help.fioritracker.org/V2020/asis/SPS02/inst-cen/'
        compatibleAsisManRel: 'SPS02'
        compatibleAsisManLink: 'https://help.fioritracker.org/V2020/asis/SPS02/inst-man/'