site_name: Fiori Tracker Business
nav:
    - Catalog Import: ci/FPS01/main.md
    - Installation: inst.md
    - FAQ: faq.md 
theme: 
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
plugins:
  - macros
extra_css:
  - stylesheets/extra.css
extra:
  prod:
    ci:
      name: 'Catalog Import'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: ''
  