site_name: Fiori Tracker Business
nav:
    - Catalog Import: ci/FPS01/main.md
    - Installation: inst.md
theme: 
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
plugins:
  - macros
  - search
extra:
  prod:
    ci:
      name: 'Catalog Import'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ''
  